### ISSUE TITLE
hi,why not get your model to test

### ISSUE THREAD

**Issue by anthonyyuan** [vchoutas/smplx#1]
I use hotmail.com to register your website ,but nothing ,I want to test it

**Comment by vchoutas** [comment]
Could you please send us an e-mail from that address so that we can check what is the problem?

**Comment by maoyali** [comment]
![2019-06-28 17-14-49屏幕截图](https://user-images.githubusercontent.com/31682925/60331958-5af49c80-99c8-11e9-8aa6-fc8be07544c3.png)
it seems that I cann't download the models now.

**Comment by vchoutas** [comment]
@maoyali Could you please try again now?

**Comment by maoyali** [comment]
It's ok, thanks~

**Comment by johndpope** [comment]
close this
