### ISSUE TITLE
npz files missing for SMPL-H model

### ISSUE THREAD

**Issue by monajalal** [vchoutas/smplx#10]
Could you please share the npz files for SMPL-H model?

I get the following error:

```
[jalal@goku smplx]$ python examples/demo.py --model-folder /scratch3/3d_pose/humanpose/SMPL_models/models --model-type="smplh" --plot-joints=True --gender="female" --use-face-contour=True
Traceback (most recent call last):
  File "examples/demo.py", line 138, in <module>
    use_face_contour=use_face_contour)
  File "examples/demo.py", line 33, in main
    ext=ext)
  File "/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/smplx/body_models.py", line 99, in create
    return SMPLH(model_path, **kwargs)
  File "/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/smplx/body_models.py", line 468, in __init__
    smplh_path)
AssertionError: Path /scratch3/3d_pose/humanpose/SMPL_models/models/smplh/SMPLH_FEMALE.npz does not exist!
[jalal@goku smplx]$ ls /scratch3/3d_pose/humanpose/SMPL_models/models/smplh/
total 254740
drwxrwx---. 4 jalal cs-grad      4096 Sep 24 17:33 ..
-rwx------. 1 jalal cs-grad 130422893 Sep 24 17:33 SMPLH_male.pkl
drwxr-xr-x. 2 jalal cs-grad        64 Sep 24 17:34 .
-rwx------. 1 jalal cs-grad 130423021 Sep 24 17:34 SMPLH_female.pkl

```

**Comment by dimtziwnas** [comment]
For legacy reasons, the original PKL files need to be converted to NPZ.
The procedure is described in the read_me file here:
https://github.com/vchoutas/smplx#downloading-the-model

It will point you to the converting script, that is here:
https://github.com/vchoutas/smplx/blob/master/tools/README.md

**Comment by monajalal** [comment]
@dimtziwnas I have done the conversion to MANO however, for converting the smplh pkl files to npz files, what script do you use? I found this https://github.com/VUmcCGP/wisecondor/issues/33#issuecomment-320912217 but seems might not be correct always.

**Comment by monajalal** [comment]
so I untarred the smplh.tar.xz from SMPLH website. and in the female folder it had model.npz and I renamed it to SMPLH_FEMALE.npz, after using it I get this error:

```
[jalal@goku smplx]$ python examples/demo.py --model-folder /scratch3/3d_pose/humanpose/SMPL_models/models --model-type="smplh" --plot-joints=True --gender="female" --use-face-contour=True
Traceback (most recent call last):
  File "examples/demo.py", line 138, in <module>
    use_face_contour=use_face_contour)
  File "examples/demo.py", line 33, in main
    ext=ext)
  File "/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/smplx/body_models.py", line 99, in create
    return SMPLH(model_path, **kwargs)
  File "/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/smplx/body_models.py", line 491, in __init__
    left_hand_components = data_struct.hands_componentsl[:num_pca_comps]
AttributeError: 'Struct' object has no attribute 'hands_componentsl'

```

**Comment by dimtziwnas** [comment]
Did you download the version that says "for AMASS"?  (special version of ICCV'19 work)

If yes, please download by clicking on "Models & code" and repeat.  This link will give you the original SIGA'17 PKL files, which are the ones that you should be using.

**Comment by monajalal** [comment]
ok so I deleted everything and only downloaded "Models & code" zip file. When I extract it, there is no .NPZ file. Could you please email me the npz files or tell me what script do you use to create them?

`[jalal@goku SMPLH-fix]$ unzip mano_v1_2.zip 
Archive:  mano_v1_2.zip
   creating: mano_v1_2/
  inflating: mano_v1_2/.DS_Store     
  inflating: mano_v1_2/._.DS_Store   
  inflating: mano_v1_2/LICENSE.txt   
  inflating: mano_v1_2/__init__.py   
   creating: mano_v1_2/models/
  inflating: mano_v1_2/models/LICENSE.txt  
  inflating: mano_v1_2/models/MANO_LEFT.pkl  
  inflating: mano_v1_2/models/MANO_RIGHT.pkl  
  inflating: mano_v1_2/models/SMPLH_female.pkl  
  inflating: mano_v1_2/models/SMPLH_male.pkl  
  inflating: mano_v1_2/models/info.txt  
   creating: mano_v1_2/webuser/
  inflating: mano_v1_2/webuser/LICENSE.txt  
  inflating: mano_v1_2/webuser/README.txt  
  inflating: mano_v1_2/webuser/__init__.py  
   creating: mano_v1_2/webuser/hello_world/
  inflating: mano_v1_2/webuser/hello_world/MANO___hello_world.py  
  inflating: mano_v1_2/webuser/hello_world/MANO___render.py  
  inflating: mano_v1_2/webuser/hello_world/SMPL+H___hello_world.py  
  inflating: mano_v1_2/webuser/hello_world/SMPL+H___render.py  
  inflating: mano_v1_2/webuser/lbs.py  
  inflating: mano_v1_2/webuser/posemapper.py  
  inflating: mano_v1_2/webuser/serialization.py  
  inflating: mano_v1_2/webuser/smpl_handpca_wrapper.py  
  inflating: mano_v1_2/webuser/smpl_handpca_wrapper_HAND_only.py  
  inflating: mano_v1_2/webuser/verts.py  
[jalal@goku SMPLH-fix]$ ls mano_v1_2/models/
total 262212
-rwx------. 1 jalal cs-grad 130422893 Nov 22  2017 SMPLH_male.pkl
-rwx------. 1 jalal cs-grad 130423021 Nov 22  2017 SMPLH_female.pkl
-rwx------. 1 jalal cs-grad        95 Nov 22  2017 info.txt
-rwx------. 1 jalal cs-grad      4330 Nov 26  2017 LICENSE.txt
-rwx------. 1 jalal cs-grad   3821356 May 14  2018 MANO_RIGHT.pkl
-rwx------. 1 jalal cs-grad   3821391 May 14  2018 MANO_LEFT.pkl
drwx------. 4 jalal cs-grad       137 Jan 17  2019 ..
drwxr-xr-x. 2 jalal cs-grad       158 Jan 17  2019 .
`

I downloaded the link that is in blue now.
![Screenshot from 2019-09-25 13-40-36](https://user-images.githubusercontent.com/1892917/65625613-26c65300-df9a-11e9-9552-3a76e7b55867.png)

**Comment by dimtziwnas** [comment]
You downloaded the right thing, now you have the PKL files.

As I pointed above, now you need to run converting script, to turn these PKL files into NPZ:
https://github.com/vchoutas/smplx/blob/master/tools/README.md

**Comment by JanaldoChen** [comment]
@monajalal I meet the problem too, when I use the smplh. But I add the **--ext pkl**, it's OK now. For example:
`python examples/demo.py --model-folder $SMPLH_FOLDER --model-type smplh --ext pkl  --gender female --plot-joints True`

**Comment by 22036435** [comment]
Hi I need joints_mat_SMPLH.pkl file to be converted into npz file how can I do it?
