### ISSUE TITLE
What is the center of rotation of the MANO model?

### ISSUE THREAD

**Issue by fabienbaradel** [vchoutas/smplx#101]
Hi,
Thanks for your amazing work. As far as I understand PELVIS is the center of rotation of the SMPL/SMPL-H/SMPL-X models but you do not give the center of rotation for the MANO model...
It seems that the wrist is not the center of rotation but I am not able to find it by my own.
Could you tell me more about the center of rotation of MANO?
Thanks a lot,

**Comment by fabienbaradel** [comment]
It seems to be the ```wrist``` but I am not 100% sure. Please correct me.
Thanks

**Comment by vchoutas** [comment]
The root joint for MANO is indeed the wrist.
