### ISSUE TITLE
`transfer_model.py` mangles output on a test file

### ISSUE THREAD

**Issue by gngdb** [vchoutas/smplx#113]
I tried to convert the [AMASS sample data](https://github.com/nghorbani/amass/blob/master/support_data/github_data/amass_sample.npz) from SMPL-H to SMPL-X using the `transfer_model` tool provided. I followed these steps:

1. Write the original SMPL-H poses to `.obj` files, one per pose, [using trimesh to export](https://github.com/gngdb/smplx/blob/master/transfer_model/write_obj.py#L85)
2. Run the command from the transfer_model docs [here](https://github.com/vchoutas/smplx/tree/master/transfer_model#smplh-to-smpl-x) after editing the config to [this](https://github.com/gngdb/smplx/blob/master/config_files/smplh2smplx_as.yaml)
3. After that's complete I tried to visualize one of these poses using the SMPL-X body model in this repository

Example output:

![](https://github.com/gngdb/smplx/blob/master/transfer_model/notes/smplx_fit.png?raw=true)

My full notes on trying to get this to run are [here](https://github.com/gngdb/smplx/blob/master/transfer_model/DEBUG_NOTES.md). Could you provide any pointers as to what I'm doing wrong? I see that AMASS was recently converted to SMPL-X, was this the tool that was used? Can you give an example of how that was performed?

**Comment by gngdb** [comment]
It turns out this is because when I wrote the `.obj` files I didn't set `process=False` in `Trimesh`. My notes are [here](https://github.com/gngdb/smplx/blob/master/transfer_model/DEBUG_NOTES.md#10th-february-2022).

**Comment by leeskyed** [comment]
> It turns out this is because when I wrote the `.obj` files I didn't set `process=False` in `Trimesh`. My notes are [here](https://github.com/gngdb/smplx/blob/master/transfer_model/DEBUG_NOTES.md#10th-february-2022).

It works. Thanks.
