### ISSUE TITLE
How to conver 'keypoints3d' to 'smpl_poses' and 'smpl_trans' ?

### ISSUE THREAD

**Issue by zhangsanfeng86** [vchoutas/smplx#126]
Hi @vchoutas 
Thank you for your wonderful work!

With the help of smpl.forward().joints , 'smpl_poses' and 'smpl_trans' conver to 'keypoints3d' .
But How to conver 'keypoints3d' to 'smpl_poses' and 'smpl_trans' ?

**Comment by minhnhatvt** [comment]
Hi, converting from 3d keypoints to SMPL poses is an inverse problem (which is also referred to as inverse kinematics) and thus it is much harder than the forward problem. This code might be helpful for you: https://github.com/CalciferZh/Minimal-IK

**Comment by zhangsanfeng86** [comment]
Thanks for your quick and useful reply!
