### ISSUE TITLE
127 joint names?

### ISSUE THREAD

**Issue by wangzheallen** [vchoutas/smplx#14]
Hi, based on https://github.com/vchoutas/smplx/issues/8
the providing files: https://github.com/vchoutas/smplx/issues/8 
has 144 joints names, however, I get 127 joints when using smplx, 
which is also shown: https://github.com/vchoutas/smplx/issues/4
May I know the 127 joints setting  joints names?
or is that the first 127 joint names from 144 joints setting?

**Comment by vchoutas** [comment]
@wangzheallen They are the first 127 joints. The other 17 can be returned if you use the face contour.

**Comment by wangzheallen** [comment]
Thanks for the reply!
