### ISSUE TITLE
Failed to run demo.py with smplx head bun

### ISSUE THREAD

**Issue by hwy1992129** [vchoutas/smplx#147]
I want to run smplx demo.py with the model without had bun. It raises the error as follow, "AttributeError: 'Struct' object has no attribute 'hands_componentsl'".
Does the model only work with SOMA/MoSh/AMASS?

**Comment by tpsmpi** [comment]
We just added a new version which is compatible with this codebase to the SMPL-X website download area, Please check.
The previously available version was only compatible with the SOMA/MoSh/AMASS codebase.
