### ISSUE TITLE
Where I can get the correspondence betweent the texture map and smplx?

### ISSUE THREAD

**Issue by maoyali** [vchoutas/smplx#16]
Thanks for your code! Is there any way to get the texture map of smplx?

**Comment by quyanqiu** [comment]
Maybe you need to do it yourself,you may need to use maya or 3dmax to cut UV map your self,the format just like smpl

**Comment by ikvision** [comment]
I was able to plug the uv_map in https://github.com/CalciferZh/SMPL/issues/5#issuecomment-548713487 into smpl 6890 vertices model and it seems to work fine with textures.
My understanding is that the vertices order of SMPL is constant for many different implementation of SMPL.

**Comment by AIdeveloper-oz** [comment]
@ikvision How did you do that? Can you explain me the steps and code changes if there are any?

**Comment by ikvision** [comment]
In the example below I take the vertices faces from SMPLX and save its mesh to an obj file with vertex texture (vt tag).
```
import numpy as np
import trimesh
import trimesh.exchange

input_path = '/tmp'
output_path = '/tmp'
uv_table = np.load(os.path.join(input_path,'uv_table.npy'))
mesh = trimesh.Trimesh(vertices,faces,visual=trimesh.visual.TextureVisuals(uv=uv_table)
export_obj = trimesh.exchange.export_obj(mesh,include_texture=True)

mesh_filename_path = os.path.join(output_path,'out.obj')
with open(mesh_filename_path,'w') as file_obj:
    trimesh.util.write_encoded(file_obj, export_obj)
```

In a mesh viewer one can add a texture.png file of that should be mapped correctly for most vertices

**Comment by quyanqiu** [comment]
@ikvision interesting，you mean the uv map that being used by the origin smpl model can be correctly adapted by smplx?
Can you show me some result of your smplx rendering result after add some texture image?

**Comment by quyanqiu** [comment]
@ikvision I dont know whether your code is wrong or my understanding is ambiguous,may be you mean **SMPL** but not **SMPLX**,because the uv table adpated from original smpl model is the dimension of 6890,which is the number of vertices of original smpl model,but SMPLX has 10475 vertices,so when I run your code and take vertics and face from SMPLX, python told me array is out of boundary,which could not being used

**Comment by vchoutas** [comment]
@maoyali Right now SMPL-X has no texture map. I will update the Readme should one be created.

**Comment by ikvision** [comment]
> @ikvision I dont know whether your code is wrong or my understanding is ambiguous,may be you mean **SMPL** but not **SMPLX**,because the uv table adpated from original smpl model is the dimension of 6890,which is the number of vertices of original smpl model,but SMPLX has 10475 vertices,so when I run your code and take vertics and face from SMPLX, python told me array is out of boundary,which could not being used

Indeed I was referring to SMPL model of 6890 used in SMPLX as part of the SPIN project [https://github.com/nkolot/SPIN/blob/277892a91e74af004c74457cd294bd102972f9b0/models/smpl.py#L23](url)

**Comment by neonb88** [comment]
> In the example below I take the vertices faces from SMPLX and save its mesh to an obj file with vertex texture (vt tag).
> 
> ```
> import numpy as np
> import trimesh
> import trimesh.exchange
> 
> input_path = '/tmp'
> output_path = '/tmp'
> uv_table = np.load(os.path.join(input_path,'uv_table.npy'))
> mesh = trimesh.Trimesh(vertices,faces,visual=trimesh.visual.TextureVisuals(uv=uv_table)
> export_obj = trimesh.exchange.export_obj(mesh,include_texture=True)
> 
> mesh_filename_path = os.path.join(output_path,'out.obj')
> with open(mesh_filename_path,'w') as file_obj:
>     trimesh.util.write_encoded(file_obj, export_obj)
> ```
> 
> In a mesh viewer one can add a texture.png file of that should be mapped correctly for most vertices

This is now "`trimesh.exchange.obj`" wherever the original commenter wrote "`trimesh.exchange`"

**Comment by fabienbaradel** [comment]
Thanks @ikvision that's very interesting. Do you know where I can find image files of texture?

**Comment by ikvision** [comment]
@fabienbaradel a simple vertices texture for SMPL can be found in:
https://github.com/facebookresearch/DensePose/issues/116#issuecomment-424978125
More diverse textures are part of surreal:
https://github.com/gulvarol/surreal/blob/master/download/files/files_smpl_data.txt

**Comment by fabienbaradel** [comment]
Thanks @ikvision for your answer :)

**Comment by quyanqiu** [comment]
now smplx support texture map and did have texture coordinate。@fabienbaradel

**Comment by fabienbaradel** [comment]
Nice, do you know where I can download the corresponding uv_map for SMPLX?

**Comment by quyanqiu** [comment]
@fabienbaradel  from their project page https://smpl-x.is.tue.mpg.de/

**Comment by Shreeshail-Hingane** [comment]
> @fabienbaradel from their project page https://smpl-x.is.tue.mpg.de/

I see the following files for the uv map:
1] a .obj file which contains two texture variables: `vt (11313, 2)` and `ft (20908,3)`.
2] a png file which contains the uv map.

I have a different png file. How do I get the corresponding `ft`?

**Comment by Shreeshail-Hingane** [comment]
alternatively, given I have a png file with the required texture, how do I add this texture to a mesh and visualize it?

**Comment by Shreeshail-Hingane** [comment]
@haiderasad If you want to create your own texture file (like this [file](https://github.com/qzane/textured_smplx/blob/main/data/obj1/texture_smplx.png)), see this repo: https://github.com/qzane/textured_smplx (though I have not used it personally)

If you already have a .png texture file and want to add this texture to a mesh, you can use the MPI Mesh library (https://github.com/MPI-IS/mesh). The `Mesh` class of this library has a `.set_texture_image()` method, to which you can pass the .png texture file as argument, and then use the `MeshViewer` class to visualize the mesh.

**Comment by haiderasad** [comment]
I have the texture file ,i only need to know how to get clothed ouput from
smplify-x using this texture.png

**Comment by Shreeshail-Hingane** [comment]
> @haiderasad If you want to create your own texture file (like this [file](https://github.com/qzane/textured_smplx/blob/main/data/obj1/texture_smplx.png)), see this repo: https://github.com/qzane/textured_smplx (though I have not used it personally)
> 
> If you already have a .png texture file and want to add this texture to a mesh, you can use the MPI Mesh library (https://github.com/MPI-IS/mesh). The `Mesh` class of this library has a `.set_texture_image()` method, to which you can pass the .png texture file as argument, and then use the `MeshViewer` class to visualize the mesh.

then do the latter step as mentioned in my answer above.

**Comment by pengHTYX** [comment]
> @fabienbaradel from their project page https://smpl-x.is.tue.mpg.de/

hi, i find that smplx_uv.obj contains 10475 vertices and 11313 vt.  I wonder why the numbers of them are not consistant? How can i map the vertices to the texture map through the uv coordiante in this case? thx

**Comment by areiner222** [comment]
@pengHTYX - I believe there are duplicated vertices corresponding to the ends of the seams generated when constructing the texture map. I've found that if you use trimesh to load, you should see 11313 vertices / texture uv verts. If you run `mesh.merge_vertices(merge_tex=True)`, that should give you the original vertices in the same order (with the same mesh connectivity) as the underlying model

**Comment by YigitAras** [comment]
> @pengHTYX - I believe there are duplicated vertices corresponding to the ends of the seams generated when constructing the texture map. I've found that if you use trimesh to load, you should see 11313 vertices / texture uv verts. If you run `mesh.merge_vertices(merge_tex=True)`, that should give you the original vertices in the same order (with the same mesh connectivity) as the underlying model

I am facing the same issue where the .obj file has 10475 vertices but 11313 VT entries. The merge_vertices works but I was unable to find a way to extract the VT coordinates from trimesh. Do you know how that can be achieved?

**Comment by bruce2233** [comment]
> > [@pengHTYX](https://github.com/pengHTYX) - I believe there are duplicated vertices corresponding to the ends of the seams generated when constructing the texture map. I've found that if you use trimesh to load, you should see 11313 vertices / texture uv verts. If you run `mesh.merge_vertices(merge_tex=True)`, that should give you the original vertices in the same order (with the same mesh connectivity) as the underlying model
> 
> I am facing the same issue where the .obj file has 10475 vertices but 11313 VT entries. The merge_vertices works but I was unable to find a way to extract the VT coordinates from trimesh. Do you know how that can be achieved?

same problem, how to fix it, thanks.
