### ISSUE TITLE
Different UV tables between smplx_uv.obj and blender-addon

### ISSUE THREAD

**Issue by JunfengLiu1** [vchoutas/smplx#160]
I want to using my own txture on smplx model.However,when using the texture map generated by this [repo](https://github.com/qzane/textured_smplx) on smplx blender plugin,the result seems not good.The screenshot:
![1](https://user-images.githubusercontent.com/122666174/232484702-afc9accb-5a5d-4c1a-830d-1d71c200de19.png)
But when it comes to smplx_uv.obj downloaded from official website,the result was good:
![2](https://user-images.githubusercontent.com/122666174/232485035-8d804e1f-5711-42c4-8c27-1a870aff074a.png)
Then I got the uv table of these two model:
one from smplx_uv.obj
![smplx_uv](https://user-images.githubusercontent.com/122666174/232485458-f1a66fee-5fbe-43d4-b0bd-dc715dbcd13b.png)
one from blender plugin
![SMPLX-mesh-neutral](https://user-images.githubusercontent.com/122666174/232485550-023f906e-f080-476d-818d-20054974cae2.png)
Obviously,they are different in the part of head.Anyone know the reason?Thanks a lot.

**Comment by tpsmpi** [comment]
SMPL-X Blender plugin uses an updated UV map which is more backwards compatible to SMPL UV map and is compatible with the sample Meshcapade reference textures we use. This UV map is different from the original UV map released for SMPL-X Python. Note that If you need different UV mapping in Blender then you can do that with https://docs.blender.org/manual/en/latest/scene_layout/object/editing/link_transfer/copy_uvmaps.html

**Comment by JunfengLiu1** [comment]
Thank you so much,sir!It really help me.
