### ISSUE TITLE
Missing translation when converting from SMPL-X to SMPL

### ISSUE THREAD

**Issue by AndresCasado** [vchoutas/smplx#168]
When converting from SMPL-X to SMPL, the `transl` parameter is set to `None`. This is due to the bug fixed in #148 

Just opening the issue in case somebody else is trying to make this conversion and can't find the cause. Can be closed when #148 is merged

Edit: wrong PR mentioned

**Comment by Orange-Ctrl** [comment]
I still get the transl: 'None' after fixing the bug, how can this happen😭

**Comment by MinJunKang** [comment]
Any fix for this? I am also suffering with this issue.

**Comment by MinJunKang** [comment]
I found the reason for this. At [Line](https://github.com/vchoutas/smplx/blob/566532a4636d9336403073884dbdd9722833d425/transfer_model/transfer_model.py#L393), the body_model_output contains transl of None and this will overwrite var_dict to have transl of None.

By adding body_model_output.transl = var_dict['transl'] before [Line](https://github.com/vchoutas/smplx/blob/566532a4636d9336403073884dbdd9722833d425/transfer_model/transfer_model.py#L393) will resolve this.

**Comment by AndresCasado** [comment]
As I say in my initial message, the fix is in https://github.com/vchoutas/smplx/pull/148

The object `body_model_output` has `transl` set to `None` because the function that builds it forgot to set the translation. As you can see in the current code, there is no `transl` parameter in the output.

https://github.com/vchoutas/smplx/blob/566532a4636d9336403073884dbdd9722833d425/smplx/body_models.py#L1289-L1299

If you change the file `smplx/body_models.py` and add `transl=transl`, as https://github.com/vchoutas/smplx/pull/148 does, it should work correctly.

**Comment by MinJunKang** [comment]
@AndresCasado Thanks for pointing out again! Your PR looks much better than my revision.

**Comment by AndresCasado** [comment]
Closed, as https://github.com/vchoutas/smplx/pull/148 is merged
