### ISSUE TITLE
Training own Mano model from scratch

### ISSUE THREAD

**Issue by wetoo-cando** [vchoutas/smplx#171]
Hello,

I would like to re-train the MANO model from scratch using my own dataset.
Is there code available to do this?

Cross-ref. to the same unanswered question in another repo: https://github.com/otaheri/MANO/issues/11

Thanks!

**Comment by dimtziwnas** [comment]
Thanks for your interest.  Unfortunately, we cannot release the training code (IP reasons).  Sorry for the inconvenience.

**Comment by wetoo-cando** [comment]
Ok thanks @dimtzionas
