### ISSUE TITLE
Converting SMPL Texture to SMPLX Texture

### ISSUE THREAD

**Issue by Mrchen116** [vchoutas/smplx#177]
Hello,

I am working with both SMPL and SMPLX models and facing a challenge in texture conversion. I have textures designed for the SMPL model, and I attempted to directly apply these textures to the SMPLX model. However, I encountered a significant issue with alignment, particularly around the face area, where the textures do not map correctly, leading to visible misalignment.

Given the differences in vertex counts and structures between SMPL and SMPLX models, I am seeking guidance on how to modify or adapt SMPL textures to fit the SMPLX model accurately. Is there a method, tool, or workflow that can aid in this conversion process, especially to address the facial misalignment? Any advice or pointers would be greatly appreciated.

**Comment by tpsmpi** [comment]
You can try the UV map from the SMPL-X Blender add-on which is more backwards compatible to SMPL. See #160 for details.
For even better quality you can use tools like Blender to convert between different UV map layouts (Cycles, bake texture map), assuming you have aligned source and target meshes.
