### ISSUE TITLE
SMPL has 45 joints?

### ISSUE THREAD

**Issue by wangsen1312** [vchoutas/smplx#18]
When I run the demo, I found the SMPL model has 45 joints? It should be 24?

**Comment by vchoutas** [comment]
SMPL has 24 joints. The remaining 21 points are vertices selected to match some 2D keypoint annotations

**Comment by wangsen1312** [comment]
@vchoutas Thank you for your response.
I found the first 24 joints correspond with the SMPL joints, do you have the other 21 annotations?

**Comment by vchoutas** [comment]
They should be: 'nose',  'right_eye', 'left_eye', 'right_ear', 'left_ear', 'left_big_toe', 'left_small_toe',    'left_heel',  'right_big_toe',  'right_small_toe',  'right_heel' and the left, right hand finger tips. For SMPL the latter should not be very useful. You can actually see the order in the [vertex_joint_selector](https://github.com/vchoutas/smplx/blob/2144d5ca0272275e1b6f82af2a476d1f2c606814/smplx/vertex_joint_selector.py#L38) script.

**Comment by wangsen1312** [comment]
@vchoutas got it, Thank you!

**Comment by Kena-2r4t** [comment]
@vchoutas Where can I get blend weights of all vertices for each of these 45 joints ?
