### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by willie1997** [vchoutas/smplx#2]
Hi，
Thanks for your work. When I ran demo.py, I met this error:
![image](https://user-images.githubusercontent.com/39046939/59581163-9b216880-9106-11e9-8dfe-7ca3123ef645.png)
 
![image](https://user-images.githubusercontent.com/39046939/59581195-b5f3dd00-9106-11e9-8232-4a9c87abf619.png)
It seems like sth. wrong with the opengl but I simpely followed the introduction and  sucessfully installed trimesh, pyrender and smplx. Could you help me please? 
Thanks a lot!

**Comment by vchoutas** [comment]
@willie1997 I am not sure what causes that. [In this comment](https://github.com/mmatl/pyrender/issues/18#issuecomment-487478858) a similar error is reported. Please try the solutions suggested by the author of pyrender. Meanwhile, I will update the example 
to use some other library for 3D visualization (e.g. matplotlib).
