### ISSUE TITLE
correspondences of MANO vertices to SMPL-X vertices

### ISSUE THREAD

**Issue by taggeli** [vchoutas/smplx#20]
Do you guys provide the correspondences of the MANO vertices to the vertices of the SMPL-X model? Thanks

**Comment by liwenssss** [comment]
Same question. I want to get the MANO parameters from the SMPL-H model.But I cant find how to get the global orientation of the hand .

**Comment by dimtziwnas** [comment]
Thanks for the request, if this is not urgent, we will come back to this in a few days after the ECCV deadlines.

**Comment by vchoutas** [comment]
@taggeli Sorry for the late reply. The correspondences can be found on the website. An example visualization script can be found [here](https://github.com/vchoutas/smplx/blob/master/examples/vis_mano_vertices.py).
@liwenssss To get the global orientation of the hand you simply have to multiply the rotation matrices of its parents in the kinematic chain.
