### ISSUE TITLE
Cannot use the face contour

### ISSUE THREAD

**Issue by rlczddl** [vchoutas/smplx#28]
I created a smplx object by set use_face_contour as true, then i forward the beta para and the expression para(all batch size is 20), but i got an error as fllows:
RunTime Error: invalid argument 7, equal number of batches expected at /torch/aten/src/THC/generic/THCTensorMathBlas.cu:523. If i set use_face_contour is false, this error disappeared.

**Comment by dhruvrajsaharan** [comment]
hi @rlczddl so why was the error? also why is use_face_countour used, what are its benefits
