### ISSUE TITLE
global_orient also leads to translation

### ISSUE THREAD

**Issue by fa9r** [vchoutas/smplx#36]
Hey, I noticed that using global_orient in SMPL will also slightly translate the model as opposed to only rotating it. Is that intended?

Below you can see a comparison of two sets of mesh vertices, one rotated using global_orient param in SMPL.foward() [teal], and the other one rotated by applying scipy.Rotation.from_rotvec on the vertices [orange]. I also compared the results with cv2.Rodrigues which leads to similar results as scipy.

![smplx_vs_scipy](https://user-images.githubusercontent.com/23118541/89538200-8fa56b00-d7fa-11ea-8a82-faf5b265a57c.png)

**Comment by vchoutas** [comment]
@fa9r What is your center of rotation when using scipy or cv2?

**Comment by fabienbaradel** [comment]
@vchoutas what is the center of rotation (i.e joint name(s)) when rotating SMPL using the global_orient argument?
Thanks

**Comment by robincourant** [comment]
Hi,
I'm encountering the same issue. 
Could you clarify how to correctly apply a rigid transform to `global_orient`, please?

**Comment by robincourant** [comment]
If anyone encounters the same issue, here’s a workaround to compensate for the induced translation when rotating by R (i.e., the `global_orient` rotation is applied relative to the root joint rather than (0,0,0)).

Hope this helps:

```
J_regressor = smpl_model.J_regressor
v_shaped = smpl_model.forward_shape(betas).v_shaped
origins = torch.einsum("bik,ji->bjk", [v_shaped, J_regressor])[:, 0]
shift = origins - torch.einsum("ij,bj->bi", R, origins)

rotated_transl = torch.einsum("ij,bj->bi", R, transl.float()) - shift
rotated_global_orient = torch.einsum("ij,...jk->...ik", R, global_orient)
```
