### ISSUE TITLE
python: can't open file 'setup.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by seyeeet** [vchoutas/smplx#39]
after doing
```
pip install smplx[all]
```
and then 
```
git clone https://github.com/vchoutas/smplx
```
do i need to do `cd smplx` and then do `python setup.py install
` ? because otherwise I get the `python: can't open file 'setup.py': [Errno 2] No such file or directory` erorr

**Comment by vchoutas** [comment]
@seyeeet You don't have to do both to install the package. The first should be enough to be able to use the package.
