### ISSUE TITLE
Generate a person joint model with hands?

### ISSUE THREAD

**Issue by Witek-** [vchoutas/smplx#41]
How can I generate a joint model of a person along with feet and hands? I have no need for a 3D mesh.

**Comment by vchoutas** [comment]
What do you mean by joint model? Hands are already there for SMPL+H/SMPL-X.

**Comment by Witek-** [comment]
What I need is only the keypoints (or joints) including fingers, and not the mesh. How can I get them without building the mesh model?

**Comment by vchoutas** [comment]
Right now we don't have support for that. You could build your own function by taking parts of the lbs forward pass.
