### ISSUE TITLE
Difference between SMPLX and SMPLXLayer classes

### ISSUE THREAD

**Issue by AndresCasado** [vchoutas/smplx#42]
I'm currently studying the model to try to use it for a project and I can't understand the difference between the SMPLX and SMPLXLayer classes.

More concretely, why does SMPLX use angle-axis format and SMPLXLayer rotation matrix format for joint rotations? Are there any other differences like this? Which one should I use?

Thanks in advance.

**Comment by vchoutas** [comment]
SMPLXLayer is meant to be used as a layer in a neural network, e.g. [ExPose](https://expose.is.tue.mpg.de/). 
You can use whichever suits you for your use case. 
Axis-angles were used for legacy reasons, in principle you can use any rotation representation you want.

**Comment by AndresCasado** [comment]
I guess that the only real difference then is that layers are meant to be used with batched data, right? Close the issue after this last question is answered, please.

Thank you very much.

**Comment by vchoutas** [comment]
Both can be used with batch data. The plain SMPL-X module stores pose and shape parameters internally, while the layer expects them as input.
