### ISSUE TITLE
SMPL and SMPLX

### ISSUE THREAD

**Issue by Lixz123456** [vchoutas/smplx#45]
hello .would you be kind to tell me about the vertices between the SMPL and SMPL-X model?

**Comment by Lixz123456** [comment]
can you help me?
I would like to know the body part of the the SMPLX has the same topology with the SMPL ?

**Comment by vchoutas** [comment]
@Lixz123456 SMPL and SMPL-X have the same vertices up to the neck. We will release code with the mapping between the two models soon.

**Comment by Lixz123456** [comment]
You are so kind!!
thanks you very very very very very much!!
I hope to see it soon~
you mean the  sequence number of the SMPL body is  consistent with SMPLX

**Comment by iluvrachel** [comment]
@vchoutas can i directly feed SMPL's theta & beta to SMPLX?

**Comment by zhuhaozh** [comment]
@vchoutas waiting for the mapping between smplx and smpl :)

**Comment by vchoutas** [comment]
@iluvrachel No, you cannot do that. 
@zhuhaozh We have released the code to transfer between the models.

**Comment by JordenQiao** [comment]
could you tell me where is the code to transfer between the models @vchoutas

**Comment by vchoutas** [comment]
@JordenQiao It is in the transfer_model subfolder.
