### ISSUE TITLE
why the joints of default smplx pose are not symmetric

### ISSUE THREAD

**Issue by senlinuc** [vchoutas/smplx#49]
gender='neutral'
![image](https://user-images.githubusercontent.com/32592255/98441363-b4cab200-2138-11eb-9d2b-fc36c8aaaa5d.png)

**Comment by MichaelJBlack** [comment]
This is a known problem with SMPL-X, which will be addressed in future model releases.  So stay tuned.

**Comment by nuntipat** [comment]
@senlinuc @MichaelJBlack May I know how the plot was made? as I'm working on retargeting joint rotations from smplify-x to other rigged model and I've found that it is a bit off. I think that it is due to the mismatch of the joint position in smplify-x's model and my model.

**Comment by senlinuc** [comment]
> @senlinuc @MichaelJBlack May I know how the plot was made? as I'm working on retargeting joint rotations from smplify-x to other rigged model and I've found that it is a bit off. I think that it is due to the mismatch of the joint position in smplify-x's model and my model.

examples/demo.py
