### ISSUE TITLE
Can I get the part info of smplx? 

### ISSUE THREAD

**Issue by zhuhaozh** [vchoutas/smplx#50]
Thanks for your awesome work! 
I would like to get the semantic part info of smplx,  but I can't find it. Can you tell me where can I get this? or how to  generate by myself?

**Comment by qiji77** [comment]
I have the same problem

**Comment by vchoutas** [comment]
@zhuhaozh one way to do this is to run np.argmax(self.lbs_weights, axis=1). This will give you a V-sized matrix, with labels from 0 to 54. The names of the 55 parts correspond to the first 55 joints names from [here](https://github.com/vchoutas/smplx/blob/f4206853a4746139f61bdcf58571f2cea0cbebad/smplx/joint_names.py#L17).
