### ISSUE TITLE
Separate Face training

### ISSUE THREAD

**Issue by ankarako** [vchoutas/smplx#51]
Hi,

Thanks for the great work.
(Not really an issue but) I would like to ask if there is a way for using smplx as a 3DMM for the head (i.e. use only head data and parameters).
Is there a fast out-of-the-box way to do this or should I try to separate the head of the model (and their corresponding parameters) according to the head joints?

Thank you very much.

**Comment by TimoBolkart** [comment]
Hi,

The head of SMPL-X is [FLAME](flame.is.tue.mpg.de), which is a standalone 3DMM for the head. You also find several code packages that build on top of FLAME [here](https://flame.is.tue.mpg.de/downloads). I hope that answers your question

**Comment by ankarako** [comment]
Hi,

Thanks for your response. I know that FLAME is the head of SMPL-X (and MANO its hands). But if I'm not wrong, according to the paper, SMPL-X was re-trained (and not just "stitched" together). So, SMPL-X's expression space could be different than FLAME's for example, right?

Anyways, thanks again for you response.

**Comment by TimoBolkart** [comment]
Hi,

Indeed, SMPL-X was re-trained which means the identity shape space for the head of SMPL-X and the identity shape space of FLAME differ. The jaw pose and the expression parameters of SMPL-X and FLAME however coincide. We leverage that fact actually in our [SMPL-X regressor using body-driven attention](https://github.com/vchoutas/expose) work, where facial expression and jaw pose are refined from a head-specific network.

**Comment by ankarako** [comment]
Hi again, 

Thank you very much for the more elaborate response. 
(I actually wanted to optimize both for FLAME and SMPL-X (face only) and compare them).
