### ISSUE TITLE
How to generate human body pose given pose keypoints detected by openpose and an existing smplx human model?

### ISSUE THREAD

**Issue by JunFang-NWPU** [vchoutas/smplx#52]
Hi,

Suppose I already have a smplx human body model, given the pose, hand, and face detected by openpose, how to generate corresponding pose of the smplx human body mode?

Thanks.

**Comment by vchoutas** [comment]
You would need to fit SMPL-X to the keypoints using [SMPLify-X](https://github.com/vchoutas/smplify-x).
