### ISSUE TITLE
Unable to locate corresponding 'main.py' when trying to transfer SMPL-X models to SMPL using 'transfer_model'

### ISSUE THREAD

**Issue by zerychao** [vchoutas/smplx#53]
Hi,

I'm trying to find ways to convert SMPL-X models to SMPL and noticed the updates in this repo on transfer between models in SMPL family. Unfortunately, I don't think the provided [_Using the code_](https://github.com/vchoutas/smplx/blob/master/transfer_model/README.md#using-the-code) section of the `README.md` file inside `transfer_model` directory is making any sense to me since I cannot find the mentioned `main.py` script. Trying to run `transfer_model.py` or `__main__.py` (though it seems to be something prepared for building a package or something and not for directly running but that seems to be where some argument parsing happens) inside `transfer_model` with the same arguments only gets me errors like

```
Traceback (most recent call last):
  File "transfer_model/transfer_model.py", line 26, in <module>
    from .utils import get_vertices_per_edge
ModuleNotFoundError: No module named '__main__.utils'; '__main__' is not a package
```

```
Traceback (most recent call last):
  File "transfer_model/__main__.py", line 30, in <module>
    from .config import parse_args
ModuleNotFoundError: No module named '__main__.config'; '__main__' is not a package
```

which are indicating that's just not right.

What am I doing wrong? I'm using Python 3.7 virtualenv on Windows 10.

Thanks in advance! @vchoutas

**Comment by vchoutas** [comment]
@zerychao Sorry for that, I made a mistake in the README. You should run transfer model as a module from the top-level of the smplx repository:
`python -m transfer_model --exp-cfg CONFIG`
I have updated the README just now. Please let me know if the problem persists. Again sorry for the mistake.

**Comment by zerychao** [comment]
No problem! But it seems that one of the dependencies `psbody` is not Windows-friendly and preventing the module from running. I'll switch to Linux and try again sometime. Have a nice day.

**Comment by kaufManu** [comment]
FWIW, the `psbody` dependency isn't really needed. It is only imported once in the file `data/datasets/mesh.py` but the import is actually never used. So you can just comment it out. This way I was able to run the code on Windows.
