### ISSUE TITLE
Position of left elbow key point is not right?

### ISSUE THREAD

**Issue by Aaron20127** [vchoutas/smplx#59]
I found that the key point of the left elbow are quite different from the right elbow.

**Comment by vikramjit-sidhu** [comment]
I faced the same issue, the left elbow keypoint is incorrect

**Comment by vchoutas** [comment]
@Aaron20127 We are aware of the asymmetry of the joints. I will let you know if and when this issue gets resolved.

**Comment by ND0X** [comment]
This issue occurred within the models:
- smplx-male-basic
- smplx-male-se
- smplx-male
- smplx-neutral-basic
- smplx-neutral-se
- smplx-neutral
