### ISSUE TITLE
visualize problem

### ISSUE THREAD

**Issue by sulei1998** [vchoutas/smplx#62]
Thanks for your awesome work!
I wonder know how to visualize a hand with arm.
I know when i use open3d to visualize a human model, I can use:
```python
mesh.vertices = o3d.utility.Vector3dVector(output.vertices)
mesh.triangles = o3d.utility.Vector3iVector(human_model.faces)
```
But i don't know if i want to visualize the right hand with the arm, how can i get the right vertices and faces.

**Comment by ZhengdiYu** [comment]
> Thanks for your awesome work! I wonder know how to visualize a hand with arm. I know when i use open3d to visualize a human model, I can use:
> 
> ```python
> mesh.vertices = o3d.utility.Vector3dVector(output.vertices)
> mesh.triangles = o3d.utility.Vector3iVector(human_model.faces)
> ```
> 
> But i don't know if i want to visualize the right hand with the arm, how can i get the right vertices and faces.

What is human_model.faces
