### ISSUE TITLE
How to convert from FLAME shape to SMPLX betas params?

### ISSUE THREAD

**Issue by foamliu** [vchoutas/smplx#66]

**Comment by vchoutas** [comment]
You can optimize the SMPL-X betas to match the FLAME head. We provide the mapping between the SMPL-X and FLAME vertices in the Downloads section of the SMPL-X website.

**Comment by komenchuk** [comment]
@foamliu Hey! Have you figured out how this can be done? I've been sitting on this problem for 2 days

**Comment by DESEOUMAIGA** [comment]
@komenchuk Same here!

**Comment by conallwang** [comment]
I implement a initial version in https://github.com/conallwang/flame2smplx.

**Comment by conallwang** [comment]
I have implemented a initial version in https://github.com/conallwang/flame2smplx.
