### ISSUE TITLE
Importing error after updating to v0.1.27 due to missing loguru

### ISSUE THREAD

**Issue by ly015** [vchoutas/smplx#67]
Hi,

Thanks for your great work. It seems that the latest v0.1.27 version added dependency on loguru, which however would not be automatically installed when installing smplx by pip. This causes an error when importing smplx.

Best

**Comment by carlosedubarreto** [comment]
I fixed it using 
`pip install loguru`

**Comment by ly015** [comment]
> I fixed it using
> `pip install loguru`

Yes. My concern is that a project built upon smplx will have to manually add loguru into its dependencies, which is not "used" in the project. This is not good for dependency management.

**Comment by vchoutas** [comment]
@ly015 Thanks for bringing this up, i have removed the import.
