### ISSUE TITLE
SMPLH joint names

### ISSUE THREAD

**Issue by fabienbaradel** [vchoutas/smplx#69]
Hi,
Thanks for your amazing work!
Could you provide the 73 joint names given by the SMPLH model? I guess there are not the 73 first names of this [file](https://github.com/vchoutas/smplx/blob/master/smplx/joint_names.py).

**Comment by vchoutas** [comment]
@fabienbaradel  You can find the joint names [here](https://github.com/vchoutas/smplx/blob/43561ecabd23cfa70ce7b724cb831b6af0133e6e/smplx/joint_names.py#L166).
They are essentially the same, minus the jaw and eyes that are not present in SMPL+H.

**Comment by fabienbaradel** [comment]
Thanks a lot!

**Comment by wang-zm18** [comment]
Why not 52 joints in SMPLH? 15 joints for each hand + 22 body joints (same as the original SMPL)? Thank you!

**Comment by MengHao666** [comment]
> Why not 52 joints in SMPLH? 15 joints for each hand + 22 body joints (same as the original SMPL)? Thank you!

Any idea now?

**Comment by Dipankar1997161** [comment]
> > Why not 52 joints in SMPLH? 15 joints for each hand + 22 body joints (same as the original SMPL)? Thank you!
> 
> Any idea now?

The original smpl has 24 joints. Adding 15 hand joints, the using the 3 face joints and remaining are taken from the smplx leg joints to cover the whole body

**Comment by nnop** [comment]
Where is the reference? @Dipankar1997161

**Comment by nnop** [comment]
> Why not 52 joints in SMPLH? 15 joints for each hand + 22 body joints (same as the original SMPL)? Thank you!

Have you figure this out?

**Comment by Dipankar1997161** [comment]
Actually people just take the desired number of joints as per their
requirements.
I have seen in many cases that for smplh 52 joints are used as the
remaining joints are less vital to the transformation
