### ISSUE TITLE
Where to get thepkl file of smpl and SMPLH?

### ISSUE THREAD

**Issue by maoyali** [vchoutas/smplx#7]
![image](https://user-images.githubusercontent.com/31682925/63644810-b2428f00-c723-11e9-9466-b82702c96145.png)
if I want to use smplh as the model type , where should I download the corresponding .pkl file, Thanks!

**Comment by monajalal** [comment]
@maoyali @vchoutas I have the same question. Where should I download the SPML and SMPLH models? I only found SMPL-X model.

**Comment by dimtziwnas** [comment]
All download links are listed in the read_me file:
https://github.com/vchoutas/smplx#downloading-the-model

To keep the email self-contained, please see below the download links:
- SMPL+H model at http://mano.is.tue.mpg.de
- SMPL (male, female) model at http://smpl.is.tue.mpg.de
- SMPL neutral model at http://smplify.is.tue.mpg.de

**Comment by monajalal** [comment]
@dimtziwnas I have downloaded the SMPL-H model from the same Website however it didn't have the npz files.

**Comment by Kairobo** [comment]
additional comments: the pkl you need is inside MANO in case you are confused

**Comment by MarilynKeller** [comment]
Building the SMPLH `.pkl` files needed some processing, we now added these files to the [Mano download page](https://mano.is.tue.mpg.de/download.php)
<img width="1125" height="235" alt="Image" src="https://github.com/user-attachments/assets/63eea1a5-5fae-4e3e-be92-d16e4099d786" />
