### ISSUE TITLE
Joints index name

### ISSUE THREAD

**Issue by ZheC** [vchoutas/smplx#8]
Hey, thank you so much for the fantastic work! Is there a documentation of all the joints name obtained from SMPLX model: https://github.com/vchoutas/smplx/blob/master/examples/demo.py#L43

I can only find the following 20 joints index name: https://github.com/vchoutas/smplx/blob/master/smplx/vertex_ids.py#L48-L69
But joints like neck, spine, are missing from the list. 

A list of names for each joint index will be really helpful! Thank you!

**Comment by vchoutas** [comment]
@ZheC I just added a [file](https://github.com/vchoutas/smplx/blob/master/smplx/joint_names.py) that contains the names. 
The first 55 correspond to the actual SMPL-X 3D skeleton joints.

**Comment by ZheC** [comment]
Thank you for adding the file! Just to make sure I understand correctly, are these joints the first 55 joints from the output 127 joints https://github.com/vchoutas/smplx/blob/master/examples/demo.py#L43

**Comment by ovshake** [comment]
Hi, thanks for the joint names. On inspecting I found that my SMPL model follows the openpose ordering which is different from the ordering you posted on that file. Do you know the reason and/or how can I convert openpose ordering to the ordering you have given?

Thanks in advance

**Comment by dongzhuoyao** [comment]
up
