### ISSUE TITLE
Pose list configured on SMPL-X

### ISSUE THREAD

**Issue by Jeongin-park** [vchoutas/smplx#85]
Hi,

May I not have seen it, but I am asking because I couldn't find it while reading the code or readme file.

I wonder if it is possible to create a fixed posture in SMPL-X. For example, if I input a specific string id as input, it creates a standard sitting pose or a standard lying pose.

If I can create a 3d pose by putting a string like 'sitting posture', can you give me some advice on Where can I find the pose list that makes up SMPL-X and how to use it?

If you help me, I think it will be very helpful.
Thank you.

**Comment by vchoutas** [comment]
@Jeongin-park that would require building a dictionary of strings to poses. Unfortunately I don't have something that works out of the box. You can probably find such poses in [BABEL](https://babel.is.tue.mpg.de/) and then build your dictionary.
