### ISSUE TITLE
How to get the location of the joints at another camera view

### ISSUE THREAD

**Issue by KelestZ** [vchoutas/smplx#88]
Hi, thanks for the impressive work.
I was wondering two questions:
1) how can I know the camera params in smpl? (e.g., FOV, transformation matrix, etc)
2) how to get the location of joints at another camera view? For instance, I'l like to globally rotate the human body to a canonical space, and I want to know the joints in the new view. (In this case, the human gestures are kept.)

**Comment by vchoutas** [comment]
The camera parameters are not part of SMPL. It's up to you to specify or estimate these parameters.
Do you want to get the parameters in the canonical space or just transform the joints? For the first one check the dropbox 
paper in the Readme, for the second you just need to apply the correct transformation on the joints.
