### ISSUE TITLE
SMPL-X UV map table problem

### ISSUE THREAD

**Issue by ahmedrasheed3995** [vchoutas/smplx#94]
I'm trying to add texture to the SMPL-X.
While loading the SMPL-X pickle file vertex count in "v_template" is 10475 while the "vt" which I suppose represents the UV table is of size 11313x2. Is there any way to associate this UV table with 10475 vertices?

**Comment by ahmedrasheed3995** [comment]
I've worked around the above-mentioned issue by using the blender and SMPLX plugin available for it.

The UV table given with the pickle file does not have the right mappings with the vertices. I created an SMPLX model using SMPLX plugin and then saved its mesh in obj format keeping the vertex order. Then loaded the obj model in python using trimesh library, from trimesh object obtained the UV table and then swapped it with the vertices/faces given in .pkl file.
Model rendered fine with 10475 vertex count (for rendering used panda3d).

There is still a little confusion on the UV table and map, when I loaded the obj file given on the official site, it had a different UV table/map with eyes map above head map but in the SMPLX plugin, the eye map is at the center of the UV map. Both screenshots are given below, 

model loaded from .obj file UV map is like this:
![Screenshot from 2021-10-14 11-38-32](https://user-images.githubusercontent.com/73983337/137265076-85222780-c6cc-44d1-a363-66ed13e0d07b.png)

model loaded from SMPLX plugin UV map is like this:
![Screenshot from 2021-10-14 11-39-41](https://user-images.githubusercontent.com/73983337/137265176-14f64372-87b9-4940-a97b-174266b271a9.png)

Now after fixing the UV table issue, UV map images were needed for rendering. I've found 3 UV mappings in the blender SMPLX plugin data folder, attached below. But was not able to find any other map over the internet, not even the three images attached. If someone knows any other UV mappings it'll be helpful, thanks.

![smplx_texture_f_alb_sscaled](https://user-images.githubusercontent.com/73983337/137263499-431b92a8-40ca-4825-b80c-937fca277cd3.png)
![smplx_texture_m_alb_sscaled](https://user-images.githubusercontent.com/73983337/137263511-c3449e29-d1bf-453c-a388-e5e3f9e4c013.png)
![smplx_texture_rainbow](https://user-images.githubusercontent.com/73983337/137263518-be5e4944-c646-446b-9da1-d259deb83cee.png)

![Screenshot from 2021-10-14 11-46-26](https://user-images.githubusercontent.com/73983337/137265745-323289ca-4c19-453f-b1e9-293888c54e63.png)

**Comment by lioo717** [comment]
> I've worked around the above-mentioned issue by using the blender and SMPLX plugin available for it.
> 
> The UV table given with the pickle file does not have the right mappings with the vertices. I created an SMPLX model using SMPLX plugin and then saved its mesh in obj format keeping the vertex order. Then loaded the obj model in python using trimesh library, from trimesh object obtained the UV table and then swapped it with the vertices/faces given in .pkl file. Model rendered fine with 10475 vertex count (for rendering used panda3d).
> 
> There is still a little confusion on the UV table and map, when I loaded the obj file given on the official site, it had a different UV table/map with eyes map above head map but in the SMPLX plugin, the eye map is at the center of the UV map. Both screenshots are given below,
> 
> model loaded from .obj file UV map is like this: ![Screenshot from 2021-10-14 11-38-32](https://user-images.githubusercontent.com/73983337/137265076-85222780-c6cc-44d1-a363-66ed13e0d07b.png)
> 
> model loaded from SMPLX plugin UV map is like this: ![Screenshot from 2021-10-14 11-39-41](https://user-images.githubusercontent.com/73983337/137265176-14f64372-87b9-4940-a97b-174266b271a9.png)
> 
> Now after fixing the UV table issue, UV map images were needed for rendering. I've found 3 UV mappings in the blender SMPLX plugin data folder, attached below. But was not able to find any other map over the internet, not even the three images attached. If someone knows any other UV mappings it'll be helpful, thanks.
> 
> ![smplx_texture_f_alb_sscaled](https://user-images.githubusercontent.com/73983337/137263499-431b92a8-40ca-4825-b80c-937fca277cd3.png) ![smplx_texture_m_alb_sscaled](https://user-images.githubusercontent.com/73983337/137263511-c3449e29-d1bf-453c-a388-e5e3f9e4c013.png) ![smplx_texture_rainbow](https://user-images.githubusercontent.com/73983337/137263518-be5e4944-c646-446b-9da1-d259deb83cee.png)
> 
> ![Screenshot from 2021-10-14 11-46-26](https://user-images.githubusercontent.com/73983337/137265745-323289ca-4c19-453f-b1e9-293888c54e63.png)

Hello, I also have the same problem. Could you please share the UV table file?

**Comment by lioo717** [comment]
@ahmedrasheed3995 Hello, I also have the same problem. Could you share the UV table file?

**Comment by ahmedrasheed3995** [comment]
I've attached the pickle file containing the UV table
[smplx_uv_map.zip](https://github.com/vchoutas/smplx/files/7451010/smplx_uv_map.zip)

**Comment by lioo717** [comment]
> I've attached the pickle file containing the UV table
> [smplx_uv_map.zip](https://github.com/vchoutas/smplx/files/7451010/smplx_uv_map.zip)
Thanks.

**Comment by lyogavin** [comment]
Hi @ahmedrasheed3995 , a quick question, your attached pickle file has a shape of (11437, 2) instead of 10475, is that correct?

**Comment by xhuan8** [comment]
@ahmedrasheed3995
Hi, how to convert this UV map image to texture, as input for renderers like neural_renderer?

the structure of texture is a single image for each face, but how to map pixel from image to faces？

texture_size = 2
textures = torch.ones(batch_size, self.faces.shape[1], texture_size, texture_size,
                      texture_size, 3, dtype=torch.float32)

**Comment by AndyVerne** [comment]
> I've attached the pickle file containing the UV table [smplx_uv_map.zip](https://github.com/vchoutas/smplx/files/7451010/smplx_uv_map.zip)

@ahmedrasheed3995 Hi, could you tell me how to generate the UV table file from the uv map images? I stuck here : (

**Comment by JunfengLiu1** [comment]
@ahmedrasheed3995 I meet the same problem.I want to add my own texture to smplx model.When using the .obj file with UV,it works fine.But when it comes to the model using smplx blender add on ,it fails, due to their uv map's shape are different in face.Is there any way to fix?Thanks a lot.
