### ISSUE TITLE
smplx download denied

### ISSUE THREAD

**Issue by sunmengnan** [vchoutas/smplx#95]
I tried some web browsers, all show as followed.
Please keep in mind that all downloads are blocked if they are not started from the website directly.
How to solve it ?

**Comment by sunmengnan** [comment]
https://psfiles.is.tuebingen.mpg.de/static_pages/no_permission,
it seems to be not allowed

**Comment by MichaelJBlack** [comment]
You need to create an account and agree to the license terms before you can download the model.

**Comment by MichaelJBlack** [comment]
I've asked our IT administrator to look into it.

**Comment by sunmengnan** [comment]
Thx

**Comment by MichaelJBlack** [comment]
It looks like our download server was updated and the links needed to be updated.  Sorry for the inconvenience.  Please try again.
